# Generated by Django 5.0.6 on 2024-06-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_remove_measurement_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydroponic_systems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='systems.hydroponicsystem'),
        ),
    ]
